"""Initial migration

Revision ID: 0533b92cc626
Revises: 
Create Date: 2025-09-16 11:27:54.560128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0533b92cc626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('total_car_slots', sa.Integer(), nullable=False),
    sa.Column('total_bike_slots', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hourly_rate_car', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('hourly_rate_bike', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hourly_rate_bike > 0', name='check_bike_rate_positive'),
    sa.CheckConstraint('hourly_rate_car > 0', name='check_car_rate_positive'),
    sa.CheckConstraint('total_bike_slots >= 0', name='check_bike_slots_positive'),
    sa.CheckConstraint('total_car_slots >= 0', name='check_car_slots_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parking_lot_active', 'parking_lots', ['is_active'], unique=False)
    op.create_index('idx_parking_lot_location', 'parking_lots', ['latitude', 'longitude'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('parking_slots',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.String(length=10), nullable=False),
    sa.Column('slot_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slot_type IN ('car', 'bike', 'truck', 'electric_car', 'electric_bike')", name='check_slot_type'),
    sa.CheckConstraint("status IN ('available', 'occupied', 'reserved', 'maintenance')", name='check_slot_status'),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'slot_number', name='unique_lot_slot')
    )
    op.create_index('idx_slot_availability', 'parking_slots', ['is_occupied', 'is_reserved', 'status'], unique=False)
    op.create_index('idx_slot_lot_type', 'parking_slots', ['lot_id', 'slot_type'], unique=False)
    op.create_index('idx_slot_status', 'parking_slots', ['status'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('days_of_week', sa.String(length=100), nullable=True),
    sa.Column('price_per_hour', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('multiplier', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('min_charge', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('max_charge', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('valid_from', sa.Time(), nullable=True),
    sa.Column('valid_until', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('high', 'normal', 'low')", name='check_priority'),
    sa.CheckConstraint("rule_type IN ('time_based', 'day_based', 'seasonal', 'demand_based')", name='check_rule_type'),
    sa.CheckConstraint('max_charge IS NULL OR max_charge >= 0', name='check_max_charge'),
    sa.CheckConstraint('min_charge IS NULL OR max_charge IS NULL OR min_charge <= max_charge', name='check_min_max_charge'),
    sa.CheckConstraint('min_charge IS NULL OR min_charge >= 0', name='check_min_charge'),
    sa.CheckConstraint('multiplier > 0', name='check_multiplier_positive'),
    sa.CheckConstraint('price_per_hour > 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'vehicle_type', 'start_time', 'end_time', 'rule_type', name='unique_pricing_rule')
    )
    op.create_index('idx_pricing_active', 'pricing_rules', ['is_active'], unique=False)
    op.create_index('idx_pricing_lot_vehicle', 'pricing_rules', ['lot_id', 'vehicle_type'], unique=False)
    op.create_index('idx_pricing_priority', 'pricing_rules', ['priority'], unique=False)
    op.create_index('idx_pricing_time', 'pricing_rules', ['start_time', 'end_time'], unique=False)
    op.create_table('bookings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled', 'expired', 'no_show')", name='check_booking_status'),
    sa.CheckConstraint('start_time < end_time', name='check_time_order'),
    sa.CheckConstraint('total_amount >= 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index('idx_booking_lot_id', 'bookings', ['lot_id'], unique=False)
    op.create_index('idx_booking_reference', 'bookings', ['booking_reference'], unique=False)
    op.create_index('idx_booking_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_booking_time_range', 'bookings', ['start_time', 'end_time'], unique=False)
    op.create_index('idx_booking_user_id', 'bookings', ['user_id'], unique=False)
    op.create_index('idx_booking_vehicle', 'bookings', ['vehicle_number'], unique=False)
    op.create_table('slot_allocations',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('allocation_type', sa.String(length=10), nullable=False),
    sa.Column('allocated_space', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("allocation_type IN ('full', 'partial')", name='check_allocation_type'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allocation_booking', 'slot_allocations', ['booking_id'], unique=False)
    op.create_index('idx_allocation_slot', 'slot_allocations', ['slot_id'], unique=False)
    op.create_index('idx_allocation_type', 'slot_allocations', ['allocation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_allocation_type', table_name='slot_allocations')
    op.drop_index('idx_allocation_slot', table_name='slot_allocations')
    op.drop_index('idx_allocation_booking', table_name='slot_allocations')
    op.drop_table('slot_allocations')
    op.drop_index('idx_booking_vehicle', table_name='bookings')
    op.drop_index('idx_booking_user_id', table_name='bookings')
    op.drop_index('idx_booking_time_range', table_name='bookings')
    op.drop_index('idx_booking_status', table_name='bookings')
    op.drop_index('idx_booking_reference', table_name='bookings')
    op.drop_index('idx_booking_lot_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('idx_pricing_time', table_name='pricing_rules')
    op.drop_index('idx_pricing_priority', table_name='pricing_rules')
    op.drop_index('idx_pricing_lot_vehicle', table_name='pricing_rules')
    op.drop_index('idx_pricing_active', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index('idx_slot_status', table_name='parking_slots')
    op.drop_index('idx_slot_lot_type', table_name='parking_slots')
    op.drop_index('idx_slot_availability', table_name='parking_slots')
    op.drop_table('parking_slots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_parking_lot_location', table_name='parking_lots')
    op.drop_index('idx_parking_lot_active', table_name='parking_lots')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
