"""Add payment tables and relationships

Revision ID: dc3f914b9e6a
Revises: 0533b92cc626
Create Date: 2025-09-16 18:33:12.311563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc3f914b9e6a'
down_revision = '0533b92cc626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_cards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_token', sa.String(length=100), nullable=False),
    sa.Column('card_last_four', sa.String(length=4), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('expiry_month', sa.String(length=2), nullable=False),
    sa.Column('expiry_year', sa.String(length=4), nullable=False),
    sa.Column('cardholder_name', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(card_last_four) = 4', name='check_card_last_four_length'),
    sa.CheckConstraint('LENGTH(expiry_month) = 2', name='check_expiry_month_length'),
    sa.CheckConstraint('LENGTH(expiry_year) = 4', name='check_expiry_year_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_card_default', 'payment_cards', ['user_id', 'is_default'], unique=False)
    op.create_index('idx_payment_card_token', 'payment_cards', ['card_token'], unique=False)
    op.create_index('idx_payment_card_user_id', 'payment_cards', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('payment_gateway', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_gateway IN ('dummy_gateway', 'stripe', 'razorpay', 'paypal', 'square')", name='check_payment_gateway'),
    sa.CheckConstraint("payment_method IN ('credit_card', 'debit_card', 'digital_wallet', 'upi', 'net_banking', 'cash')", name='check_payment_method'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded', 'partially_refunded')", name='check_payment_status'),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.CheckConstraint('refund_amount <= amount', name='check_refund_amount_valid'),
    sa.CheckConstraint('refund_amount >= 0', name='check_refund_amount_non_negative'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('idx_payment_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_index('idx_payment_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('idx_payment_gateway_transaction_id', 'payments', ['gateway_transaction_id'], unique=False)
    op.create_index('idx_payment_processed_at', 'payments', ['processed_at'], unique=False)
    op.create_index('idx_payment_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payment_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_index('idx_payment_user_id', 'payments', ['user_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gateway_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded', 'partially_refunded')", name='check_transaction_status'),
    sa.CheckConstraint("transaction_type IN ('payment', 'refund', 'partial_refund', 'adjustment')", name='check_transaction_type'),
    sa.CheckConstraint('amount != 0', name='check_amount_non_zero'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_created_at', 'payment_transactions', ['created_at'], unique=False)
    op.create_index('idx_transaction_payment_id', 'payment_transactions', ['payment_id'], unique=False)
    op.create_index('idx_transaction_processed_at', 'payment_transactions', ['processed_at'], unique=False)
    op.create_index('idx_transaction_status', 'payment_transactions', ['status'], unique=False)
    op.create_index('idx_transaction_type', 'payment_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_type', table_name='payment_transactions')
    op.drop_index('idx_transaction_status', table_name='payment_transactions')
    op.drop_index('idx_transaction_processed_at', table_name='payment_transactions')
    op.drop_index('idx_transaction_payment_id', table_name='payment_transactions')
    op.drop_index('idx_transaction_created_at', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('idx_payment_user_id', table_name='payments')
    op.drop_index('idx_payment_transaction_id', table_name='payments')
    op.drop_index('idx_payment_status', table_name='payments')
    op.drop_index('idx_payment_processed_at', table_name='payments')
    op.drop_index('idx_payment_gateway_transaction_id', table_name='payments')
    op.drop_index('idx_payment_created_at', table_name='payments')
    op.drop_index('idx_payment_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_payment_card_user_id', table_name='payment_cards')
    op.drop_index('idx_payment_card_token', table_name='payment_cards')
    op.drop_index('idx_payment_card_default', table_name='payment_cards')
    op.drop_table('payment_cards')
    # ### end Alembic commands ###
